### ISSUE TITLE
Add inclusive naming to CI?

### ISSUE THREAD

**Issue by sed-i** [canonical/observability-libs#25]
### Enhancement Proposal

pytest-operator [has](https://github.com/charmed-kubernetes/pytest-operator/blob/main/.github/workflows/tests.yaml#L7) this:
```
jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical-web-and-design/Inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"
```
